name: Slack Notify

description: "Send a Slack message if a webhook is provided; otherwise skip gracefully"

author: "Skill Tracker DevOps"

inputs:
  payload:
    description: "Slack JSON payload"
    required: true
  webhook:
    description: "Slack Incoming Webhook URL"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Skip if webhook is missing
      if: ${{ inputs.webhook == '' }}
      shell: bash
      run: |
        echo "SLACK_WEBHOOK_URL not provided; skipping Slack notification."

    - name: Send Slack notification
      if: ${{ inputs.webhook != '' }}
      uses: slackapi/slack-github-action@v1.26.0
      with:
        payload: ${{ inputs.payload }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
