name: DevOps Branch CI/CD (feature/devops-ecs)

on:
  repository_dispatch:
    types:
      - backend-devops-branch-merged
  workflow_dispatch:
    inputs:
      pr_title:
        description: 'PR Title'
        required: true
        type: string
      pr_author:
        description: 'PR Author'
        required: true
        type: string
      pr_url:
        description: 'PR URL'
        required: true
        type: string
      target_branch:
        description: 'Target Branch'
        required: true
        type: string
        default: 'feature/devops-ecs'
      commit_sha:
        description: 'Commit SHA'
        required: true
        type: string
      enable_ecs_deploy:
        description: 'Enable ECS Deployment'
        required: false
        type: boolean
        default: true
      force_full_build:
        description: 'Force Full Build'
        required: false
        type: boolean
        default: false

jobs:
  build-devops-branch:
    uses: ./.github/workflows/backend-feature-to-dev-cicd.yml
    with:
      pr_title: ${{ github.event.client_payload.pr_title || inputs.pr_title }}
      pr_author: ${{ github.event.client_payload.pr_author || inputs.pr_author }}
      pr_url: ${{ github.event.client_payload.pr_url || inputs.pr_url }}
      target_branch: ${{ github.event.client_payload.target_branch || inputs.target_branch }}
      commit_sha: ${{ github.event.client_payload.commit_sha || inputs.commit_sha }}
      enable_ecs_deploy: ${{ github.event.client_payload.enable_ecs_deploy || inputs.enable_ecs_deploy }}
      force_full_build: ${{ github.event.client_payload.force_full_build || inputs.force_full_build }}
    secrets:
      BACKEND_REPO_NAME: ${{ secrets.BACKEND_REPO_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      ARN_APP_SECRETS_JWT: ${{ secrets.ARN_APP_SECRETS_JWT }}
      ARN_APP_SECRETS_OAUTH_GOOGLE: ${{ secrets.ARN_APP_SECRETS_OAUTH_GOOGLE }}
      ARN_APP_SECRETS_MAIL: ${{ secrets.ARN_APP_SECRETS_MAIL }}
      ARN_APP_SECRETS_MQ: ${{ secrets.ARN_APP_SECRETS_MQ }}
      ARN_APP_SECRETS_REDIS: ${{ secrets.ARN_APP_SECRETS_REDIS }}
      ARN_APP_SECRETS_MONGO_ANALYTICS: ${{ secrets.ARN_APP_SECRETS_MONGO_ANALYTICS }}
      ARN_APP_SECRETS_MONGO_GAMIFICATION: ${{ secrets.ARN_APP_SECRETS_MONGO_GAMIFICATION }}
      ARN_APP_SECRETS_MONGO_NOTIFICATION: ${{ secrets.ARN_APP_SECRETS_MONGO_NOTIFICATION }}
      ARN_APP_SECRETS_POSTGRES_SCHEMAS: ${{ secrets.ARN_APP_SECRETS_POSTGRES_SCHEMAS }}