name: Workflow Dispatcher

on:
  repository_dispatch:
    types:
      - backend-feature-to-dev-merged
      - backend-dev-to-staging-merged
      - backend-staging-to-prod-merged

jobs:
  build-dev-stage:
    if: github.event.action == 'backend-feature-to-dev-merged'
    uses: ./.github/workflows/backend-feature-to-dev-cicd.yml
    with:
      pr_title: ${{ github.event.client_payload.pr_title }}
      pr_author: ${{ github.event.client_payload.pr_author }}
      pr_url: ${{ github.event.client_payload.pr_url }}
      target_branch: ${{ github.event.client_payload.target_branch }}
      commit_sha: ${{ github.event.client_payload.commit_sha }}
      enable_ecs_deploy: ${{ github.event.client_payload.enable_ecs_deploy || true }}
    secrets:
      BACKEND_REPO_NAME: ${{ secrets.BACKEND_REPO_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
